### ISSUE TITLE
ERROR: for wireshark  "host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by qknight** [linuxserver/docker-wireshark#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
docker compose up 

Should add the wireshark container to my already existing compose file and start the wireshark container so I can use it to look at my network.

## Current Behavior

```
ERROR: for wireshark  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 203, in perform_command
  File "compose\metrics\decorator.py", line 18, in wrapper
  File "compose\cli\main.py", line 1186, in up
  File "compose\cli\main.py", line 1166, in up
  File "compose\project.py", line 697, in up
  File "compose\parallel.py", line 108, in parallel_execute
  File "compose\parallel.py", line 206, in producer
  File "compose\project.py", line 679, in do
  File "compose\service.py", line 579, in execute_convergence_plan
  File "compose\service.py", line 499, in _execute_convergence_recreate
  File "compose\parallel.py", line 108, in parallel_execute
  File "compose\parallel.py", line 206, in producer
  File "compose\service.py", line 494, in recreate
  File "compose\service.py", line 612, in recreate_container
  File "compose\service.py", line 330, in create_container
  File "compose\service.py", line 939, in _get_container_create_options
  File "compose\service.py", line 1014, in _get_container_host_config
  File "docker\api\container.py", line 598, in create_host_config
  File "docker\types\containers.py", line 338, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[18132] Failed to execute script docker-compose
```

This seems to be not relevant for us, since we really want to see what is going on inside:

https://stackoverflow.com/questions/67819391/docker-compose-network-mode-and-port-binding-compatibility-issue

And this discussion here https://forums.docker.com/t/docker-errors-invalidargument-host-network-mode-is-incompatible-with-port-bindings/103492 I don't understand.

## Steps to Reproduce

1. Add the section from the README.md to your own docker-compose.yaml
2. Run docker compose up

## Environment
**OS:** Windows 10 
**CPU architecture:** x86_64
**How docker service was installed:**

Docker Desktop 4.7.1 (77678) is currently the newest version available.

## Command used to create docker container (run/create/compose/screenshot)

docker compose

**Comment by j0nnymoe** [comment]
Would be helpful if you added your docker-compose file as the template requests.

**Comment by j0nnymoe** [comment]
Although, I can probably guess the issue. You're mixing host networking and bridge port mappings which is causing the conflict but also host networking does not work on windows so you need to remove the host networking from your compose.
So you have 2 issues here:

1. mixing 2 different network types
2. using host networking on windows when it doesn't support it

Solution: remove host networking line and use bridged ports or don't use windows to host our wireshark container.
